### ISSUE TITLE
Broken link to Phoenix6 API docs

### ISSUE THREAD

**Issue by sciencewhiz** [robotpy/robotpy-sphinx-plugin#8]
The link in the API docs sidebar to phoenix6 goes to: https://api.ctr-electronics.com/phoenix6/release/python/en/stable/index.html It should go to: https://api.ctr-electronics.com/phoenix6/release/python/

The link is right in _sidebar.toml, but I'm guessing the en/stable/index.html is being added somewhere automatically, which breaks it.

**Comment by virtuald** [comment]
Fixed in 731e06b99b094c9b16236b406351bf6cccee0789

**Comment by virtuald** [comment]
We don't have the doc plugin or sidebar pinned, so I retriggered some of the key API sites, so it should be mostly fixed, and as other sites are rebuilt it will get updated.
